export const SAVE_COURSES_SUCCESS = 'SAVE_COURSES_SUCCESS';
export const DELETE_COURSES_SUCCESS = 'DELETE_COURSES_SUCCESS';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const DELETE_ALL = 'DELETE_ALL';
